
apiVersion: v1
kind: Service
metadata:
  name: backendservice
  namespace: backend
spec:
  selector:
    app: app-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
